apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: talos-cluster-template
spec:
  infrastructureRef:
    name: dev-talos-cluster-template
  controlPlaneRef:
    name: dev-talos-cluster-template-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxCluster
metadata:
  name: talos-cluster-template
spec:
  controlPlaneEndpoint:
    host: 192.168.100.160
    port: 6443
  ipv4Config:
    addresses:
      - 192.168.100.161-192.168.100.175
    prefix: 24
    gateway: 192.168.100.1
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-cluster-template-control-plane
spec:
  replicas: 1
  infrastructureTemplate:
    name: dev-talos-cluster-template-cp-machine
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: talos-cluster-template-workers
spec:
  clusterName: dev-talos-cluster-template
  replicas: 2
  template:
    spec:
      clusterName: dev-talos-cluster-template
      bootstrap:
        configRef:
          name: dev-talos-cluster-template-worker-config
      infrastructureRef:
        name: dev-talos-cluster-template-worker-machine
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: talos-cluster-template-ip-pool
spec:
  addresses:
    - 192.168.100.161-192.168.100.175
  gateway: 192.168.100.1
  prefix: 24


