# SOPS Configuration for GitOps Manifests
creation_rules:
  - path_regex: gitops/.*\.sops\.ya?ml$
    age: "age1rusvf26jvcv855lunxcfgectmm5va087au4s7au09hvy6h290qdqptextv"
  - path_regex: gitops/.*secret.*\.ya?ml$
    age: "age1rusvf26jvcv855lunxcfgectmm5va087au4s7au09hvy6h290qdqptextv"
