# SOPS Configuration for GitOps Manifests
creation_rules:
  - path_regex: gitops/.*\.sops\.ya?ml$
    age: "age1mznrg444sxs38v5kdtply07lhl0fqumpy380j22eje3hntpzsqzssgeghh"
  - path_regex: gitops/.*secret.*\.ya?ml$
    age: "age1mznrg444sxs38v5kdtply07lhl0fqumpy380j22eje3hntpzsqzssgeghh"
