apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: talos-cloud-controller-manager
  namespace: kube-system
  labels:
    k8s-app: talos-cloud-controller-manager
spec:
  selector:
    matchLabels:
      k8s-app: talos-cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: talos-cloud-controller-manager
    spec:
      serviceAccountName: cloud-controller-manager
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: system-node-critical
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
      containers:
        - name: talos-cloud-controller-manager
          image: ghcr.io/siderolabs/talos-cloud-controller-manager:v1.9.3
          args:
            - --v=2
            - --cloud-provider=talos
            - --cloud-config=/etc/kubernetes/talos-cloud-config.yaml
            - --use-service-account-credentials=true
            - --leader-elect=false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
